name: travel_ai
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.2
  path: ^1.8.3
  firebase_core: ^3.13.0
  cloud_firestore: ^5.5.0
  firebase_auth: ^5.3.3
  image_picker: ^0.8.8+5
  firebase_storage: ^12.3.6
  intl: ^0.18.1
  table_calendar: ^3.0.9
  fluttertoast: ^8.2.1
  http: ^1.1.0
  shared_preferences: ^2.2.2
  permission_handler: ^11.3.1
  flutter_markdown: ^0.7.0
  flutter_gemini: 3.0.0
  google_generative_ai: ^0.2.0
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.4
  font_awesome_flutter: ^10.8.0
  pdf: ^3.10.8
  printing: ^5.12.0
  open_filex: ^4.3.2
  cupertino_icons: ^1.0.8
  firebase_app_check: ^0.3.2+10
  url_launcher: ^6.2.5
  share_plus: ^11.0.0
  screenshot: ^2.1.0

flutter_icons:
  android: true
  ios: true
  image_path: assets/splash.png
  adaptive_icon_foreground: assets/splash.png
  adaptive_icon_background: "#000000"

flutter_native_splash:
  color: "#000000"
  image: assets/splash.png
  fullscreen: true
  android_12:
    image: assets/splash.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/images/admin/topAvatar.jpeg
    - assets/logo.png
    - assets/splash.png

